name: fforecast
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  #- pytorch-cuda=11.8
  - pytorch-lightning=1.9.*
  - scikit-learn=1.2.*
  - sunpy=4.1.*
  - snakemake
  - wandb
  - seaborn
  - zarr
  - xarray