data:
  augmentation: none #conservative (conservative was the original one used)
  balance_ratio: 0
  channels:
  - 0
  data_file: Data/labels_regression_24h.csv
  dim: 128
  feature_cols:
  - tot_us_flux
  - tot_flux
  - datamin
  - datamax
  - flare_rate_y
  - flare_rate_m
  - flare_rate_w
  - max_flare_72h
  - max_flare_48h
  - max_flare_24h
  file_col: filename
  flare_thresh: 1.0e-05
  flux_thresh: 15000000
  forecast_window: 24
  label: flare
  maxval:
  - 500
  regression: true
  test: '' #try test_a 
  use_zarr_dataset: false
  val_split: 0
  zarr_file: null
meta: #used for wandb logging, useless right now...
  id: None
  project: flare-forecast-regression
  resume: false
  user: margherita-lampani
model:
  checkpoint_location: null
  dropout_ratio: 0
  load_checkpoint: false
testing:
  eval: true
  savedir: results
  savefile: 24h_historical_testa_regression
training:
  batch_size: 64
  device: cpu
  devices: 1
  epochs: 100
  lr: 0.0001 
  wd: 0 #0.001 (put to 0 just for the overfitting test)

  #remember to uncomment the early stopping in train_model_regression.py after the overfitting test
